### ISSUE TITLE
Navigating via <a href="{{urlFor(page.route)}}"> with path driver reloads page

### ISSUE THREAD

**Issue by orenb** [Polymore/more-routing#22]
When using the path config for the driver, if I add an <a> link to a urlFor some page, clicking that link causes the browser to reload/re-render in order to navigate to it. By contrast, with hash based routing, the same link loads the page in-place without a browser reload.

Is this WAI? If not, any way around it, while keeping path based routing?

**Comment by nevir** [comment]
That's WAI, I don't want to have the routing lib intercept all clicks/taps on the page.  You'll want to have it call `MoreRouting.navigateTo(page.route)` at some level
